#!usr\bin\env python3  （这是一个在python环境下运行的python代码）
# author:dashan          （作者）
# coding practice      （主题）
#-*- coding ：utf-8 -*-（使用utf-8编码）
a=ord('A')
print(a)

b='新年快乐'.encode('utf-8')
print(b)

c=len(b'ABC')
d=len('中文'.encode('utf-8'))
print('c=',c,'d=',d)
